apiVersion: v2
appVersion: "1.0"
description: A Helm chart for juror-scheduler-api App
name: juror-scheduler-api
home: https://github.com/hmcts/juror-scheduler-api
version: 0.0.8
maintainers:
  - name: HMCTS juror team
dependencies:
  - name: java
    version: 4.1.4
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
